"""Enumerations owned by the BUY / WAIT / WATCH recommendation engine."""

from enum import StrEnum


class Recommendation(StrEnum):
    """Deterministic buy-timing decision. Never a guaranteed outcome."""

    BUY_NOW = "BUY_NOW"
    WAIT = "WAIT"
    WATCH = "WATCH"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class RuleId(StrEnum):
    """Stable identifiers for every explicit recommendation rule.

    Reasons cite these ids so a decision can be traced to the exact rule that fired.
    """

    GATE_NO_CURRENT_PRICE = "GATE_NO_CURRENT_PRICE"
    GATE_STALE_DATA = "GATE_STALE_DATA"
    GATE_MISSING_DATA = "GATE_MISSING_DATA"
    GATE_INSUFFICIENT_HISTORY = "GATE_INSUFFICIENT_HISTORY"

    BUY_FAVORABLE_PERCENTILE = "BUY_FAVORABLE_PERCENTILE"
    BUY_STRONG_PERCENTILE = "BUY_STRONG_PERCENTILE"
    BUY_NEAR_HISTORICAL_LOW = "BUY_NEAR_HISTORICAL_LOW"
    BUY_STRONG_NEAR_HISTORICAL_LOW = "BUY_STRONG_NEAR_HISTORICAL_LOW"
    BUY_BELOW_AVERAGES = "BUY_BELOW_AVERAGES"
    BUY_PREDICTION_NO_MATERIAL_SAVINGS = "BUY_PREDICTION_NO_MATERIAL_SAVINGS"
    BUY_FALLING_TREND = "BUY_FALLING_TREND"

    WAIT_UNFAVORABLE_PERCENTILE = "WAIT_UNFAVORABLE_PERCENTILE"
    WAIT_ABOVE_AVERAGES = "WAIT_ABOVE_AVERAGES"
    WAIT_PREDICTED_SAVINGS = "WAIT_PREDICTED_SAVINGS"
    WAIT_UPCOMING_SALE = "WAIT_UPCOMING_SALE"
    WAIT_RISING_TREND = "WAIT_RISING_TREND"

    WATCH_NEUTRAL_HISTORY = "WATCH_NEUTRAL_HISTORY"
    WATCH_CONFLICTING_SIGNALS = "WATCH_CONFLICTING_SIGNALS"
    WATCH_WEAK_FAVORABLE = "WATCH_WEAK_FAVORABLE"
    WATCH_EVENT_NOT_CREDIBLE = "WATCH_EVENT_NOT_CREDIBLE"
    WATCH_PREDICTION_LOW_CONFIDENCE = "WATCH_PREDICTION_LOW_CONFIDENCE"
    WATCH_PREDICTION_MISSING = "WATCH_PREDICTION_MISSING"
    WATCH_NEUTRAL_TREND = "WATCH_NEUTRAL_TREND"

    PRED_UNUSED_MISSING = "PRED_UNUSED_MISSING"
    PRED_UNUSED_INSUFFICIENT = "PRED_UNUSED_INSUFFICIENT"
    PRED_UNUSED_LOW_CONFIDENCE = "PRED_UNUSED_LOW_CONFIDENCE"
    PRED_UNUSED_NO_PRICE = "PRED_UNUSED_NO_PRICE"


class InsufficientRecommendationReason(StrEnum):
    """Machine-readable reason a recommendation was withheld rather than guessed."""

    NO_CURRENT_PRICE = "no_current_price"
    STALE_DATA = "stale_data"
    MISSING_DATA = "missing_data"
    INSUFFICIENT_HISTORY = "insufficient_history"
