import type {
  ComparedOfferRead,
  DataFreshnessRead,
  HistoryObservationRead,
  MonthlyBucketRead,
  MonthlyPriceIntelligenceRead,
  ProductHistoryRead,
  ProductPricesRead,
  ProductRead,
  ProductRecommendationRead,
  ProductSaleIntelligenceRead,
  ProductSalePricePredictionRead,
  ProductSearchHit,
  ProductSearchPage,
  ProductVariantRead,
  RetailerRead,
  VariantHistoryRead,
} from "@/lib/types/api";

/** Clearly labelled fixture data for frontend tests. Not real retailer prices. */

export const FIXTURE_NOW = "2026-08-27T12:00:00+00:00";

export const freshnessFresh: DataFreshnessRead = {
  status: "fresh",
  as_of: FIXTURE_NOW,
  observed_at: FIXTURE_NOW,
  age_seconds: 120,
  oldest_observation: FIXTURE_NOW,
  newest_observation: FIXTURE_NOW,
  stale_offer_count: 0,
  missing_observation_count: 0,
  offer_count: 1,
};

export const productFixture: ProductRead = {
  id: "11111111-1111-1111-1111-111111111111",
  name: "Fictional Orchard Aurora 5G Smartphone",
  slug: "fictional-orchard-aurora-5g",
  description: "Fixture product used only in frontend tests.",
  brand_id: null,
  category_id: null,
  is_active: true,
  created_at: FIXTURE_NOW,
  updated_at: FIXTURE_NOW,
};

export const variantFixture: ProductVariantRead = {
  id: "22222222-2222-2222-2222-222222222222",
  product_id: productFixture.id,
  name: "128 GB · Midnight",
  attributes: { storage: "128 GB", colour: "Midnight" },
  variant_key: "colour=midnight|storage=128gb",
  is_active: true,
  created_at: FIXTURE_NOW,
  updated_at: FIXTURE_NOW,
};

export const retailerFixture: RetailerRead = {
  id: "33333333-3333-3333-3333-333333333333",
  name: "Fictional Mock Mart A",
  slug: "mock-retailer-a",
  website_url: "https://mock-retailer-a.example.test",
  country_code: "IN",
  is_active: true,
  created_at: FIXTURE_NOW,
  updated_at: FIXTURE_NOW,
};

export const searchHitFixture: ProductSearchHit = {
  product: productFixture,
  variant: variantFixture,
  retailer: retailerFixture,
  seller: {
    id: "44444444-4444-4444-4444-444444444444",
    retailer_id: retailerFixture.id,
    name: "Fictional Mock Mart A",
    external_seller_id: "A-SELLER-0",
    is_first_party: true,
    is_active: true,
    created_at: FIXTURE_NOW,
    updated_at: FIXTURE_NOW,
  },
  retailer_product_id: "55555555-5555-5555-5555-555555555555",
  retailer_sku: "A-MOB-1001",
  displayed_price: "59999.00",
  mrp: "69999.00",
  effective_price: null,
  currency: "INR",
  availability: "in_stock",
  source_url: "https://mock-retailer-a.example.test/A-MOB-1001",
  observed_at: FIXTURE_NOW,
  source_type: "official_api",
  confidence: "high",
};

export function searchPageFixture(
  items: ProductSearchHit[] = [searchHitFixture],
): ProductSearchPage {
  return {
    items,
    total: items.length,
    limit: 50,
    offset: 0,
    query: "aurora",
    failures: [],
    consulted_retailer_ids: ["mock-retailer-a"],
  };
}

export const offerFixture: ComparedOfferRead = {
  offer_id: "66666666-6666-6666-6666-666666666666",
  variant_id: variantFixture.id,
  retailer_id: retailerFixture.id,
  retailer_slug: retailerFixture.slug,
  retailer_name: retailerFixture.name,
  retailer_product_id: searchHitFixture.retailer_product_id,
  seller: {
    seller_id: searchHitFixture.seller?.id ?? null,
    name: "Fictional Mock Mart A",
    is_first_party: true,
    is_active: true,
    quality_score: 80,
  },
  displayed_price: "59999.00",
  mrp: "69999.00",
  discount_percentage: null,
  coupon_discount: null,
  payment_discount: null,
  cashback: null,
  delivery_fee: null,
  platform_fee: null,
  effective_price: "59999.00",
  unverified_estimated_price: null,
  unverified_price_kind: null,
  source_effective_price: null,
  price_kind: "verified_effective",
  availability: "in_stock",
  source_url: searchHitFixture.source_url,
  source_type: "official_api",
  observation_timestamp: FIXTURE_NOW,
  confidence: "high",
  observation_confidence: "high",
  freshness: freshnessFresh,
  adjustments: [],
  currency: "INR",
  rank: 1,
  is_available: true,
  can_win_verified_ranking: true,
};

export const pricesFixture: ProductPricesRead = {
  product_id: productFixture.id,
  variants: [
    {
      variant_id: variantFixture.id,
      variant_key: variantFixture.variant_key,
      offers: [offerFixture],
      lowest_verified_offer: offerFixture,
      ranking_reason: {
        criterion: "verified_effective_price",
        reason: "Lowest verified effective price among in-stock fixture offers.",
        tie_breakers_applied: [],
        selected_offer_id: offerFixture.offer_id,
      },
      data_freshness: freshnessFresh,
    },
  ],
  lowest_verified_offer: offerFixture,
  ranking_reason: {
    criterion: "verified_effective_price",
    reason: "Lowest verified effective price among in-stock fixture offers.",
    tie_breakers_applied: [],
    selected_offer_id: offerFixture.offer_id,
  },
  data_freshness: freshnessFresh,
  as_of: FIXTURE_NOW,
};

function metric(value: string, status: "available" | "insufficient_history" = "available") {
  return {
    value_kind: "CALCULATED" as const,
    status,
    value: status === "available" ? value : null,
    unit: "INR",
    window_days: 7,
    observation_count: status === "available" ? 4 : 0,
    calculated_at: FIXTURE_NOW,
    insufficient:
      status === "insufficient_history"
        ? { code: "no_qualifying_observations" as const, reason: "No qualifying observations." }
        : null,
    extra: {},
  };
}

function monthlyBucket(
  month: number,
  name: string,
  status: "available" | "insufficient_history" = "insufficient_history",
  value: string | null = null,
): MonthlyBucketRead {
  const stats = metric(value ?? "0", status);
  return {
    month,
    month_name: name,
    retailer_id: null,
    retailer_slug: null,
    retailer_name: null,
    years_used: status === "available" ? [2025, 2026] : [],
    observation_count: status === "available" ? 4 : 0,
    minimum: stats,
    average: stats,
    median: stats,
    maximum: stats,
    historical_low: stats,
    historical_high: stats,
    volatility: stats,
  };
}

const MONTH_NAMES = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const monthlyFixture: MonthlyPriceIntelligenceRead = {
  value_kind: "CALCULATED",
  months: MONTH_NAMES.map((name, index) =>
    index === 0
      ? monthlyBucket(1, name, "available", "54999.00")
      : index === 1
        ? monthlyBucket(2, name, "available", "58999.00")
        : monthlyBucket(index + 1, name),
  ),
  retailer_months: [],
  best_buying_month: monthlyBucket(1, "January", "available", "54999.00"),
  best_buying_month_price: {
    ...metric("54999.00"),
    extra: { month: 1, month_name: "January" },
  },
  qualifying_observation_count: 8,
  calculated_at: FIXTURE_NOW,
  method: "CALCULATED from qualifying verified observations grouped by calendar month-of-year.",
  predicted: null,
};

export const observationFixture = (
  overrides: Partial<HistoryObservationRead> = {},
): HistoryObservationRead => ({
  value_kind: "OBSERVED",
  id: "77777777-7777-7777-7777-777777777777",
  product_id: productFixture.id,
  product_variant_id: variantFixture.id,
  retailer_id: retailerFixture.id,
  retailer_slug: retailerFixture.slug,
  retailer_name: retailerFixture.name,
  retailer_product_id: searchHitFixture.retailer_product_id,
  seller_id: searchHitFixture.seller?.id ?? null,
  source_url: searchHitFixture.source_url,
  source_type: "official_api",
  observed_at: FIXTURE_NOW,
  created_at: FIXTURE_NOW,
  currency: "INR",
  displayed_price: "59999.00",
  effective_price: "59999.00",
  effective_price_value_kind: "CALCULATED",
  mrp: "69999.00",
  analysis_price: "59999.00",
  analysis_price_field: "displayed_price",
  availability: "in_stock",
  confidence: "high",
  qualifies_for_calculations: true,
  ...overrides,
});

export const variantHistoryFixture: VariantHistoryRead = {
  product_id: productFixture.id,
  product_variant_id: variantFixture.id,
  variant_key: variantFixture.variant_key,
  observations: {
    items: [
      observationFixture({
        id: "aaaaaaa1-aaaa-aaaa-aaaa-aaaaaaaaaaa1",
        observed_at: "2026-08-20T12:00:00+00:00",
        displayed_price: "62000.00",
        analysis_price: "62000.00",
      }),
      observationFixture({
        id: "aaaaaaa2-aaaa-aaaa-aaaa-aaaaaaaaaaa2",
        observed_at: "2026-08-27T12:00:00+00:00",
        displayed_price: "59999.00",
        analysis_price: "59999.00",
      }),
    ],
    total: 2,
    limit: 200,
    offset: 0,
  },
  qualifying_observation_count: 2,
  excluded_unverified_observation_count: 0,
  current_observation: observationFixture(),
  average_7d: metric("61000.00"),
  average_30d: metric("61000.00"),
  average_90d: metric("61000.00"),
  average_180d: metric("61000.00"),
  historical_low: {
    ...metric("59999.00"),
    snapshot_id: null,
    observed_at: FIXTURE_NOW,
    retailer_id: retailerFixture.id,
    seller_id: null,
    source_url: null,
  },
  historical_high: {
    ...metric("62000.00"),
    snapshot_id: null,
    observed_at: FIXTURE_NOW,
    retailer_id: retailerFixture.id,
    seller_id: null,
    source_url: null,
  },
  current_price_percentile: { ...metric("0"), unit: "percentile" },
  volatility: { ...metric("0.02"), unit: "ratio" },
  percentage_change: { ...metric("-3.23"), unit: "percent" },
  price_drop: {
    value_kind: "CALCULATED",
    status: "available",
    drop_occurred: true,
    percentage_change: "-3.23",
    current_price: "59999.00",
    baseline_price: "62000.00",
    current_observed_at: FIXTURE_NOW,
    baseline_observed_at: "2026-08-20T12:00:00+00:00",
    current_snapshot_id: null,
    baseline_snapshot_id: null,
    baseline_retailer_id: retailerFixture.id,
    baseline_seller_id: null,
    baseline_description: "previous qualifying observation on the same retailer listing",
    observation_count: 2,
    calculated_at: FIXTURE_NOW,
    insufficient: null,
  },
  trend: {
    value_kind: "CALCULATED",
    status: "available",
    direction: "falling",
    implied_percent_change: "-3.23",
    slope_per_day: "-286.00",
    method: "linear_regression",
    observation_count: 2,
    first_observed_at: "2026-08-20T12:00:00+00:00",
    last_observed_at: FIXTURE_NOW,
    calculated_at: FIXTURE_NOW,
    insufficient: null,
  },
  monthly: monthlyFixture,
  data_freshness: freshnessFresh,
  provenance: {
    observations_value_kind: "OBSERVED",
    calculations_value_kind: "CALCULATED",
    predicted: null,
    predicted_value_kind: null,
    analysis_price_rule: "verified_effective_else_displayed",
    price_drop_baseline: "previous_qualifying_observation",
    trend_method: "linear_regression",
  },
  calculated_at: FIXTURE_NOW,
};

export const historyFixture: ProductHistoryRead = {
  product_id: productFixture.id,
  variants: [variantHistoryFixture],
  data_freshness: freshnessFresh,
  provenance: variantHistoryFixture.provenance,
  calculated_at: FIXTURE_NOW,
  predicted: null,
};

export const insufficientHistoryFixture: ProductHistoryRead = {
  product_id: productFixture.id,
  variants: [
    {
      ...variantHistoryFixture,
      observations: { items: [], total: 0, limit: 200, offset: 0 },
      qualifying_observation_count: 0,
      current_observation: null,
      average_7d: metric("0", "insufficient_history"),
      average_30d: metric("0", "insufficient_history"),
      average_90d: metric("0", "insufficient_history"),
      average_180d: metric("0", "insufficient_history"),
      historical_low: {
        ...metric("0", "insufficient_history"),
        snapshot_id: null,
        observed_at: null,
        retailer_id: null,
        seller_id: null,
        source_url: null,
      },
      historical_high: {
        ...metric("0", "insufficient_history"),
        snapshot_id: null,
        observed_at: null,
        retailer_id: null,
        seller_id: null,
        source_url: null,
      },
      current_price_percentile: metric("0", "insufficient_history"),
      volatility: metric("0", "insufficient_history"),
      percentage_change: metric("0", "insufficient_history"),
      trend: {
        ...variantHistoryFixture.trend,
        status: "insufficient_history",
        direction: "insufficient_history",
        insufficient: {
          code: "no_qualifying_observations",
          reason: "No qualifying observations.",
        },
      },
      data_freshness: {
        ...freshnessFresh,
        status: "missing",
        observed_at: null,
        newest_observation: null,
        oldest_observation: null,
        offer_count: 0,
      },
    },
  ],
  data_freshness: {
    ...freshnessFresh,
    status: "missing",
    observed_at: null,
    newest_observation: null,
  },
  provenance: variantHistoryFixture.provenance,
  calculated_at: FIXTURE_NOW,
  predicted: null,
};

const TIMING_DISCLAIMER =
  "Projected sale dates and prices are evidence-based estimates and are not guaranteed retailer announcements.";

export const saleIntelligenceFixture: ProductSaleIntelligenceRead = {
  product_id: productFixture.id,
  as_of: FIXTURE_NOW,
  disclaimer: TIMING_DISCLAIMER,
  predicted: null,
  variants: [
    {
      product_id: productFixture.id,
      product_variant_id: variantFixture.id,
      variant_key: variantFixture.variant_key,
      current_cheapest_retailer_id: retailerFixture.id,
      current_cheapest_retailer_slug: retailerFixture.slug,
      current_cheapest_retailer_name: retailerFixture.name,
      current_cheapest_price: "59999.00",
      current_effective_price: "59999.00",
      current_availability: "in_stock",
      calendar: [
        {
          sale_family: "catalogue:fixture-major-sale",
          display_name: "Fixture Major Sale",
          sale_type: "MAJOR",
          evidence_status: "expected",
          mapping_method: "festival_relative",
          expected_start_date: "2026-10-29T00:00:00+00:00",
          expected_end_date: "2026-11-05T23:59:59+00:00",
          confidence: "medium",
          evidence_count: 2,
          historical_years_used: [2024, 2025],
          retailer_id: null,
          occasion_id: "diwali",
          duration_days: 7,
          reason: "Historical starts clustered relative to a public festival date.",
          predicted: null,
        },
      ],
      ordinary: {
        sale_type: "ORDINARY",
        window: {
          sale_family: "catalogue:fixture-ordinary-sale",
          display_name: "Fixture Ordinary Sale",
          sale_type: "ORDINARY",
          evidence_status: "expected",
          mapping_method: "fixed_calendar",
          expected_start_date: "2026-09-08T00:00:00+00:00",
          expected_end_date: "2026-09-10T23:59:59+00:00",
          confidence: "medium",
          evidence_count: 2,
          historical_years_used: [2024, 2025],
          retailer_id: retailerFixture.id,
          occasion_id: null,
          duration_days: 2,
          reason: "Historical starts fell near a stable calendar date.",
          predicted: null,
        },
        expected_price: "57500.00",
        expected_price_value_kind: "CALCULATED",
        expected_saving: "2499.00",
        expected_saving_percentage: "4.17",
        expected_saving_value_kind: "CALCULATED",
        days_until_start: 12,
        likely_best_retailer_id: retailerFixture.id,
        likely_best_retailer_slug: retailerFixture.slug,
        likely_best_retailer_name: retailerFixture.name,
        retailer_outlooks: [],
        confidence: "medium",
        historical_reliability: "medium",
        status: "available",
        insufficient_reason: null,
      },
      major: {
        sale_type: "MAJOR",
        window: {
          sale_family: "catalogue:fixture-major-sale",
          display_name: "Fixture Major Sale",
          sale_type: "MAJOR",
          evidence_status: "expected",
          mapping_method: "festival_relative",
          expected_start_date: "2026-10-29T00:00:00+00:00",
          expected_end_date: "2026-11-05T23:59:59+00:00",
          confidence: "medium",
          evidence_count: 2,
          historical_years_used: [2024, 2025],
          retailer_id: null,
          occasion_id: "diwali",
          duration_days: 7,
          reason: "Historical starts clustered relative to a public festival date.",
          predicted: null,
        },
        expected_price: "49999.00",
        expected_price_value_kind: "PREDICTED",
        expected_saving: "10000.00",
        expected_saving_percentage: "16.67",
        expected_saving_value_kind: "CALCULATED",
        days_until_start: 63,
        likely_best_retailer_id: retailerFixture.id,
        likely_best_retailer_slug: retailerFixture.slug,
        likely_best_retailer_name: retailerFixture.name,
        retailer_outlooks: [],
        confidence: "high",
        historical_reliability: "high",
        status: "available",
        insufficient_reason: null,
      },
      expected_best_retailer: {
        retailer_id: retailerFixture.id,
        retailer_slug: retailerFixture.slug,
        retailer_name: retailerFixture.name,
        current_price: "59999.00",
        current_price_value_kind: "CALCULATED",
        availability: "in_stock",
        is_current_cheapest: true,
        expected_sale_price: "49999.00",
        expected_sale_price_value_kind: "PREDICTED",
        predicted_sale_price: "49999.00",
        predicted_lower_bound: "48000.00",
        predicted_upper_bound: "52000.00",
        predicted_confidence: 0.78,
        historical_sale_price: "51000.00",
        historical_occurrence_count: 2,
        expected_saving: "10000.00",
        expected_saving_percentage: "16.67",
        expected_saving_value_kind: "CALCULATED",
        confidence: "high",
        reliability: "medium",
        status: "available",
        insufficient_reason: null,
      },
      disclaimer: TIMING_DISCLAIMER,
      calculated_at: FIXTURE_NOW,
      predicted: null,
    },
  ],
};

export const insufficientSaleIntelligenceFixture: ProductSaleIntelligenceRead = {
  product_id: productFixture.id,
  as_of: FIXTURE_NOW,
  disclaimer: TIMING_DISCLAIMER,
  predicted: null,
  variants: [
    {
      ...saleIntelligenceFixture.variants[0],
      ordinary: null,
      major: null,
      expected_best_retailer: null,
      calendar: [],
    },
  ],
};

export const recommendationFixture: ProductRecommendationRead = {
  product_id: productFixture.id,
  as_of: FIXTURE_NOW,
  disclaimer:
    "This recommendation is a deterministic, rule-based suggestion from available observed, calculated, and (when used) predicted data. It is not a guarantee of any future price, saving, or sale outcome.",
  phase10_status: "INSUFFICIENT_DATA",
  phase10_model_version: null,
  variants: [
    {
      product_variant_id: variantFixture.id,
      recommendation: "WAIT",
      expected_saving: "10000.00",
      expected_saving_percentage: "16.67",
      confidence: 0.62,
      reasons: [
        "Recommendation is WAIT. This is not a guaranteed price or saving.",
        "Buying window is WAIT_FOR_MAJOR_SALE. Projected sale dates and prices are evidence-based estimates and are not guaranteed retailer announcements.",
      ],
      triggered_rule_ids: ["WAIT_MAJOR_SALE_WORTHWHILE"],
      disclaimer:
        "This recommendation is a deterministic, rule-based suggestion from available observed, calculated, and (when used) predicted data. It is not a guarantee of any future price, saving, or sale outcome.",
      prediction_used: false,
      insufficient: null,
      provenance: {
        current_price_value_kind: "CALCULATED",
        historical_value_kind: "CALCULATED",
        predicted_value_kind: null,
        expected_saving_value_kind: "CALCULATED",
        expected_saving_basis: "major_sale_expected_price_vs_current",
      },
      evidence: {
        current_effective_price: "59999.00",
        historical_percentile: "45.00",
        historical_low: "49999.00",
        average_30d: "61000.00",
        average_90d: "62000.00",
        trend_direction: "stable",
        predicted_sale_price: null,
        prediction_confidence: null,
        prediction_used: false,
        upcoming_sale_name: null,
        upcoming_sale_days: null,
        freshness_status: "fresh",
        qualifying_observation_count: 8,
        expected_saving_basis: "major_sale_expected_price_vs_current",
        urgency: "patient",
        buying_window: "WAIT_FOR_MAJOR_SALE",
        ordinary_sale_name: "Fixture Ordinary Sale",
        ordinary_sale_days: 12,
        major_sale_name: "Fixture Major Sale",
        major_sale_days: 63,
      },
      buying_window: "WAIT_FOR_MAJOR_SALE",
      urgency: "patient",
      ordinary_opportunity: null,
      major_opportunity: null,
    },
  ],
};

export const salePricePredictionFixture: ProductSalePricePredictionRead = {
  product_id: productFixture.id,
  as_of: FIXTURE_NOW,
  value_kind: "PREDICTED",
  is_prediction: true,
  disclaimer: "Predicted sale prices are estimates, not guarantees.",
  status: "PREDICTED",
  model_version: "fixture-not-a-trained-model",
  training_data_size: 40,
  feature_version: "features-v1",
  predictions: [
    {
      value_kind: "PREDICTED",
      is_prediction: true,
      disclaimer: "Predicted sale prices are estimates, not guarantees.",
      status: "PREDICTED",
      predicted_price: "49999.00",
      lower_bound: "48000.00",
      upper_bound: "52000.00",
      confidence: 0.78,
      model_version: "fixture-not-a-trained-model",
      training_data_size: 40,
      currency: "INR",
      as_of: FIXTURE_NOW,
      product_id: productFixture.id,
      product_variant_id: variantFixture.id,
      retailer_id: retailerFixture.id,
      seller_id: null,
      feature_version: "features-v1",
      insufficient: null,
      uncertainty_method: "validation_residuals",
    },
  ],
  insufficient: null,
};

export const insufficientPredictionFixture: ProductSalePricePredictionRead = {
  ...salePricePredictionFixture,
  status: "INSUFFICIENT_DATA",
  model_version: null,
  predictions: [],
  insufficient: { code: "no_trained_model", reason: "No trained model artifact is available." },
};
